### ISSUE TITLE
Exceptions  happeans when training on MSVD dataset

### ISSUE THREAD

**Issue by ChinaWangYu666** [layer6ai-labs/xpool#14]
We run the code on the MSVD dataset, but the code is exited without any errors and hints. The author can give me some help. Thanks very much!

**Comment by NoelVouitsis** [comment]
At one point in the code does this happen? You are likely running out of memory. What is your batch size?

**Comment by ChinaWangYu666** [comment]
> At one point in the code does this happen? You are likely running out of memory. What is your batch size?

It happens during the testing phase. I find it is  running out of memory

**Comment by NoelVouitsis** [comment]
MSVD evaluation requires a lot of memory because we perform evaulation for multiple captions per video at the same time. Inference happens on the CPU. I would suggest either using a machine with more CPU memory or experimenting on less memory intensive datasets like MSR-VTT or LSMDC. Thanks!

**Comment by EmreOzkose** [comment]
Hi @ChinaWangYu666 , I also encountered this problem during testing. You can [increase swap memory](https://askubuntu.com/a/1177939).
