### ISSUE TITLE
Question about setting

### ISSUE THREAD

**Issue by JonnyS1226** [layer6ai-labs/xpool#3]
hello, thank you for your very nice work! 
And i have a question about setting. That is, what kind of and the number of GPU you use in the experiment?
Thanks!

**Comment by NoelVouitsis** [comment]
Hi there, thank you for taking interest in our work! 
We used a single NVIDIA Titan RTX GPU with 24GB of memory for our experiments.
Thank you!

**Comment by 1024er** [comment]
> 

How long does each experiment take using one single gpu ? @NoelVouitsis

**Comment by NoelVouitsis** [comment]
It depends on the dataset. For MSR-VTT it took around 8 hours. Thanks!

**Comment by jianghaojun** [comment]
@NoelVouitsis I tried to reproduce the results on MST-VTT-9K, it took 10h to run 1 epoch(on one singe RTX3090). Do you know of any factors that may have contributed to this situation?

**Comment by NoelVouitsis** [comment]
Maybe you can experiment with batch_size and evals_per_epoch and num_workers. Also you can consider where you are storing the MSR-VTT dataset since if it's stored on a different disk the I/O can be bottleneck. Thanks!

**Comment by NoelVouitsis** [comment]
Also compressing videos to 3fps using the code in `preprocess/compress_video.py` can significantly speed up training

**Comment by jianghaojun** [comment]
Thanks for your suggestions.
