### ISSUE TITLE
Question about the validation

### ISSUE THREAD

**Issue by bighuang624** [layer6ai-labs/xpool#4]
Hi, much thanks for your nice paper and the well-organized open-resourced codebase. 
I am a beginner of the video-text retrieval area, and I noticed that you seemed to have used the test split of the datasets for validation, according to the [Line.40 of train.py](https://github.com/layer6ai-labs/xpool/blob/main/train.py#L40). I want to know if I misunderstood this, or is this the common practice in this area?
Looking forward to any response.

**Comment by NoelVouitsis** [comment]
Hi there, thank you for taking interest in our work! 
This is a convention following previous work such as CLIP4Clip [1].
Thanks!

[1] Huaishao Luo, Lei Ji, Ming Zhong, Yang Chen, Wen Lei, Nan Duan, and Tianrui Li. Clip4clip: An empirical study of clip for end to end video clip retrieval. arXiv preprint arXiv:2104.08860, 2021.
