### ISSUE TITLE
Json file in MSVD data

### ISSUE THREAD

**Issue by avinashsai** [layer6ai-labs/xpool#7]
Hi,

The MSVD link in CLIP4CLIP downloads a pickle file where as your code loads a json file. Can you provide the details on how to convert the pickle to json (eg: what keys and values are expected as part of the json and the structure of the files)?

Thank you.

**Comment by kkzhang95** [comment]
Hi, do you solve this problem?

**Comment by NoelVouitsis** [comment]
@kkzhang95 we already provide the json file under `data/MSVD/captions_msvd.json`

**Comment by kkzhang95** [comment]
> @kkzhang95 we already provide the json file under `data/MSVD/captions_msvd.json`

OK, I have found it.  Thanks a lot for your reply.
