### ISSUE TITLE
Is the value of hyper-parameter head number “num_mha_heads=1(default)” correct? 

### ISSUE THREAD

**Issue by jianghaojun** [layer6ai-labs/xpool#8]
https://github.com/layer6ai-labs/xpool/blob/6514cc712f30081108463c5d8d4d6c261a1a4a96/config/all_config.py#L52

**Comment by NoelVouitsis** [comment]
In all experiments, we set the number of heads to 1 since for our pooling mechanism it doesn't have the same interpretation as the number of heads in Transformers, and empirically it works best. Thanks!
